import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Footer from '@/components/Footer'
import Button from '@/components/Button'
import Form from '@/components/Form'
import SignIn from '@/components/SignIn'
import Facebook from '@/components/Facebook'
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>Instagram Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.bg}`}>

      <main className={`${styles.main}`}>
      
        <div className={`${styles.border}`}>
        <h1 className={styles.h1}>Welcome to...</h1>
          <div className={`${styles.img}`}>
            <Image src={'/images/instagram-icon.png'} alt="instagram logo" width={175} height={70}/>
          </div>

          <br className={styles.br}/>

        <Form/>
        <Button/>
        <p className={`${styles.or}`}>----- OR -----</p>
        <Facebook/>
        <p><Link href={'/'} className={styles.forgot}>Forgot password?</Link></p>
        </div>
        
        <div className={`${styles.new}`}>
        <SignIn/>

        </div>

        <p className={`${styles.word}`}>Get the app.</p>
        <div className={`${styles.app}`}>
        <Image src={'/images/app-icon.png'} alt="get the app on CH Play and Appstore" width={300} height={50}/>
        </div>

      </main>
      <Footer/>
      </div>
    </>
  )
}


